### ISSUE TITLE
Maximum hull mass for engineered shields is modified incorrectly

### ISSUE THREAD

**Issue by WaferMouse** [EDCD/coriolis#122]
Modifying the optimal hull mass for shields in Coriolis affects the maximum hull mass, but in-game this has no effect on the maximum hull mass.  Findings based on a level 3 enhanced low power 3D shield that has the same maximum hull mass in-game as a stock module.

**Comment by strideynet** [comment]
Will investigate.

**Comment by DaftMav** [comment]
Was about to open a new issue but looks like this one has been forgotten a bit. Would be great if this gets a fix, since Coriolis shows shield health as 0 MJ in red when you apply Enhanced Low Power mod on a shield which makes it go under the max hull mass. Considering this mod lowers the mass of the shield generator, maxing it out to G5 is very useful to explorers.

Example of current Coriolis behaviour: On an Anaconda with a 400 hull mass and a 3D shield generator, you can only apply Enhanced Low Power G2 mod. With G3 and higher it shows the maximum hull mass goes under 400 and the shield health shows 0 MJ suggesting it is impossible to do this.

This happens only with 'Enhanced Low Power' mod, all the other shield generator mods are correct and do not change the max hull mass. Perhaps the % change to 'Optimal Hull Mass' that the Enhanced Low Power mod _does_ apply, is somehow also applied to Maximum Hull Mass?

Maximum Hull Mass is the same for each version of same grade shield generator, so 4A, 4B, 4C, 4D, 4E, as well as 4C bi-weave and 4A prismatic versions are all 713 tons maximum hull mass. Here is the full list:

Shield Grade|Maximum Hull Mass (T)
-|-
1|63
2|138
3|413
4|713
5|1013
6|1350
7|2650
8|4500
