### ISSUE TITLE
Cryptoscrambler DPS wrong

### ISSUE THREAD

**Issue by strideynet** [EDCD/coriolis#185]
https://gfycat.com/GrippingSneakyAfricanclawedfrog

**Comment by felixlinker** [comment]
All numbers are entered correctly for the module but DPS should be `27.4` as opposed to `59.8`.

**Comment by felixlinker** [comment]
Rate of fire is wrong. It is 7,6/s in the gif above but coriolis says it's 16,6. This roughly corresponds to the error in DPS (besides a small deviation which could be explained by rounding).

**Comment by felixlinker** [comment]
Coriolis currently mixes together the burst rof and the "actual" rof. However, all DPS values I have seen so far, only account for rounds per shot, damage and rof where rof is the plain rof value taken from the game. This indicates, that the burst rof is more indicative for players to understand how "fast" a burst actually will be without having any impact on the overall rof.

Also, burst size does not seem to play a role for damage. The damage value seems to match the damage of one burst.

**However**, this does not seem to apply to projectile weapons. This is a bit too general, as the only case where projectile weapons fire bursts is when "Double Shot" is applied to frags. Neither Inara nor coriolis-data list any change on RoF or damage but edsy does modify the overall RoF after applying double shot.

**Comment by felixlinker** [comment]
I'm not sure, whether my assumptions about what burst rof means are right. But it seems to align quite well.

#388 is probably related.

**Comment by felixlinker** [comment]
Here some data that might be related:

![image](https://user-images.githubusercontent.com/9728715/56833365-99f25e80-686e-11e9-9e1d-c74fd0d6cce3.png)

![image](https://user-images.githubusercontent.com/9728715/56833381-a5458a00-686e-11e9-8347-4597a42360c2.png)

![image](https://user-images.githubusercontent.com/9728715/56833405-b1c9e280-686e-11e9-82e6-5e49908d3b9b.png)

**Comment by felixlinker** [comment]
I figured out, what the issue is: the rate of fire of a module is determined by three things:
1. Burst size - How many shots are fired in one volley?
2. Burst interval - How long does it take to fire in the next shot **in** one volley?
3. Fire interval - How long does it take to start the next volley after all shots of the current volley have been fired?

The rate of fire is determined by this formula: `1 / ((burstSize - 1) * burstInterval + fireInterval)`

coriolis-data is currently bugged in this scenario. It seems like `rof` of burst lasers is the reciprocal of the fire interval but for point defence and the imperial hammer it seemed to be the rate of fire as calculated above.
