### ISSUE TITLE
Some engineering values are incorrect

### ISSUE THREAD

**Issue by strideynet** [EDCD/coriolis#188]
Please feedback on this thread.

**Comment by willyb321** [comment]
hull stuff, ROF are the ones i can remember of the top of my head but they are bugged on fdevs end

**Comment by willyb321** [comment]
According to /u/DMJason from the reddit thread - Long Range applied to a Pulse Laser (maybe more) is changing the falloff to equal the max range

**Comment by ctrl-shift** [comment]
LR applying falloff equal to max range is correct. it displays same values in game.

**Comment by CMDRTheDarkLord** [comment]
Packhound Clip Size isn't reported correctly. I have two packhounds with G5 High Capacity mods. 

Both units are showing "-83.3%" on the Ammunition clip, whereas both units actually have +100% clip sizes 

Other stats look like they're reporting correctly - at least in terms of the checking that I've done. Thanks for the great work on this.

**Comment by willyb321** [comment]
@CMDRTheDarkLord do you have a /import url you can provide (put it on pastebin.com and link here pls)

**Comment by CMDRTheDarkLord** [comment]
@willyb321 Here you go:

https://pastebin.com/29KbDYCM

That's the import link straight from EDMC, and I saved the configuration and included the shortlink to the saved config. Let me know if you need anything else.

**Comment by willyb321** [comment]
Another thing - lr cannons dont have shot speed  values (probably missing the value in coriolis-data)

**Comment by awdwyn** [comment]
Power priorities and disabled modules do not match in game as of this latest update to Coriolis when the experimentals were added. Specifically I'm noticing on all my ships exported from EDMC the cargo scoop is shown disabled (it's actually not) and the power priority on my FDL huge slot is set to 1 in Coriolis while it's 3 in game.

**Comment by CMDRTheDarkLord** [comment]
Me again... I discovered that the Scan Time is not reporting on modified Kill Warrant Scanner fitted to my FdL.

I have Fast Scan Grade 5. Scan Time is reported at 10 seconds (0%), where the module is actually scanning in 2.7 seconds (-73%). All other values are correct.

Here is the Pastebin of the import: https://pastebin.com/kVbKMkLE

**Comment by willyb321** [comment]
Ok will have some time today to get some of those values fixed.1
@awdwyn check #191 thanks

**Comment by awdwyn** [comment]
Will have some time later tonight to poke around - I'll manually key in a couple of ships and export to text, then use EDMC to import those ships and export. I'l run a diff and post any irregularities. Hopefully that'll provide some useful results.

**Comment by awdwyn** [comment]
Just tested my combat FDL.

EDMC raw data: https://pastebin.com/a5rRZLni
Coriolis import from EDMC: https://eddp.co/u/V4iD7MdJ
Manual coriolis build (matches in game): https://eddp.co/u/ftsUlYMX

Results of export each from coriolis and run through kdiff (ignoring differences caused by rounding percentage values on the in-game UI from 2 decimals to 1):

- 2F MC G5 high capacity + corrosive: clip size should be +94.4, import has it at -97.78
- 0A KWS G5 fast scan: scan time should be -73.8, import has it at 0
- 5C Bi-weave shield gen G5 thermal resist: explosive should be +0.15, import at +25.08, kinetic should be -13.08, import at 15.72, thermal should be 54.75, import at 41.7
- cargo scoop enabled in game, disabled in import
- power priorities in export match in game this time - it was off before on the huge slot.

**Comment by willyb321** [comment]
Ok so there will be *another* new mod format coming with the beta. I have some [sample data](https://cdn.discordapp.com/attachments/164411501166198784/402746076303720458/LoadoutExample.json) and its not the same values so I'm not entirely sure what we should do @strideynet - continue fixing the old format only to have the effort be invalidated when the release rolls around, or hold out with the current *mostly* working mods.
👍 if you think we should wait for the new format to hit live 👎 if you think we should continue fixing

**Comment by reticenti** [comment]
To be honest, working on a new standardization would be best going forward rather than wasting time fixing something that will be out of date in 2 weeks. You guys do so much and your tool is already amazing, who cares if the percents are off by a little for a couple weeks while we wait for the new patch.  Just my opinion, feel free to disagree
