### ISSUE TITLE
Bug or Request: Experimental Effects EDEngineer Import

### ISSUE THREAD

**Issue by MBGTBenjamin** [EDCD/coriolis#312]
The experimental effects are not exported to EDEngineer. Also, the export in the beta doesn't work (is that intentional?). But apart from that, the function is very very helpful.

**Comment by willyb321** [comment]
As for experimentals not being added, that is due to them not having UUIDs, I will add them today. (They will need to be added to EDEngineer as well)

Export not working on beta is odd, can you take a screenshot of your console tab (F12) after hitting send to EDEngineer. Seems to be working fine here.

**Comment by willyb321** [comment]
I have added uuids to specials: https://github.com/EDCD/coriolis-data/commit/89ac0af57d76233e15e89c296a9173d9f89cd959

I also opened a PR over at msarilar/EDEngineer#431

**Comment by willyb321** [comment]
Fixed.

**Comment by MBGTBenjamin** [comment]
Sorry for not answering, but since the last Coriolis update I can export again.
