### ISSUE TITLE
Change random button functionality on engineering panels

### ISSUE THREAD

**Issue by Sheuzzo** [EDCD/coriolis#379]
Random button on engineer modification had more sense before 3.0 mechanics, now with incremental rolls it has less use. A way to replace it is to change the button in "manual" and , if selected, it stops the panel to overwrite manual inserted values. 

Otherwise it could be changed in "roll" button that, if pressed , does a random incremental roll and adds 1 to a counter. In this way I could chose how many rolls to try and have a preview of how my module will probably become with that many rolls

**Comment by felixlinker** [comment]
Not a final, but a first comment: As blueprints progress at a different place tied to your progress with the given engineer the progress button couldn't be implement well because a) we don't know how exactly this is working and b) we don't know your progress with an engineer.

**Comment by felixlinker** [comment]
@willyb321 I would say we leave it as is. I can't see another solution to this problem than to store on each stat whether a value was entered manually. If you want to apply an experimental effect after manual stats have been entered then you just need to re-enter values effected by the experimental.

Also it is unlikely that is even the case as ui will have you select an experimental in the first place.

I think this issue mainly comes down to the fact that we had some issues with experimentals as described in #249 but those are fixed in #386
