### ISSUE TITLE
coriolis.io is broken on firefox

### ISSUE THREAD

**Issue by Sniffy75** [EDCD/coriolis#441]
I'm using Firefox quantum, build 63.0.3 (64-bit) on Windows 10 and while https://coriolis.edcd.io/ works fine, when I go to https://coriolis.io/ as suggested, the page is completely black, nothing there at all.
I can use Chrome as a work around or continue using the coriolis.edcd.io site but it makes it difficult when people link to a build thats on the coriolis.io site since Firefox is my default browser.

**Comment by willyb321** [comment]
Try clearing your cache (not local storage) for coriolis.io

**Comment by AndrewdAzotus** [comment]
This happens for me too, Ihave cleared my cache. I find a ctrl-f5 rebuilds the page. It used to happen with persistent [local] storage where is seems to store lots of text files in "my Documents" but even with that turned off it happens since a recent update. This is on Win-10, I do not get this on Win-8.1 if that helps

**Comment by willyb321** [comment]
See #454 for more information.

**Comment by willyb321** [comment]
Will take a look at this soon.

**Comment by dmytro-shchurov** [comment]
It also returns 404 for all scripts in Chrome 71 for me. Happened few days before NY.

**Comment by willyb321** [comment]
@dmytro-shchurov you may need to clear your cache, I have some issues with Traefik (my webserver) [ref containous/traefik#3780 ]

**Comment by willyb321** [comment]
Also, I have pushed up a probable fix, so if anyone wants to help test it, feel free.
