### ISSUE TITLE
coriolis.io + shortener down

### ISSUE THREAD

**Issue by snoozybat** [EDCD/coriolis#572]
Main site buttons aint working either. Can't access to existing builds using the shortner.

**Comment by rosscarlson** [comment]
Yep, this has been an issue for at least 3 days now as I've been having folks report this on my videos (CMDR Exigeous here) - looks like a HTTP issue, perhaps a server is down.

**Comment by willyb321** [comment]
The server is infact currently down, I've been incredibly busy so haven't been able to get it back up yet.

**Comment by willyb321** [comment]
Coriolis.io should be back up now, URL shortener is still down for now. Will update when back up.

**Comment by rosscarlson** [comment]
Thanks @willyb321 - I've had dozens report this on various videos so I posted an update on my Community page to let everyone know what was going on.

I've been a server admin for 25+ years, if I can be of any assistance - including offering hosting where we have EDTutorials.com just let me know. Happy to help out as I can.

**Comment by rosscarlson** [comment]
Any update yet? Anything I/we can do to help? As I/we rely on Coriolis so much it's pretty tough to have all the links in all my videos be broken, if I need to just bite the bullet and update them all to either EDSY or to Tinyurl just let me know. Don't at all mean to be a pain, as trust me I understand how much work all this is, just hoping we can get back online soon.

Again if I can help in any way, including offering hosting for the site on the EDTutorials.com server just let me know.

~Exigeous

**Comment by willyb321** [comment]
At the moment the best way to help get the site back online would be to donate to the paypal so I can get the server back up and running and everything back to normal.

https://www.paypal.me/willb321

**Comment by rosscarlson** [comment]
So it's not a technical issue then? If it's an issue in terms of cost as I said I'm more than happy to offer you free hosting on the AWS servers where we run EDTutorials.com. These are even front-ended by Cloudflare to prevent attacks and mitigate outages and bandwidth issues. If there is some other financial issue preventing the site from coming online let me know.

I'm happy to also cover hosting/ownership of any DNS, etc. eliminating any costs for you at all. We easily have the capacity and this is a tool the entire community uses. If this is something you just won't be able to do please let me know so I can start updating all the links in my 200+ videos to point somewhere else, something I really don't want to do.

Really want to help so let me know if I can host any of it for you.

~Exigeous

**Comment by AlexandrosG** [comment]
Could you please let us know what you need to get the shortener online again? I've donated some money but I can't know if that's enough.

This is affecting both content creators and simple users that just want to look up builds.

**Comment by willyb321** [comment]
Sorry for the late reply, I've been incredibly busy IRL lately. The main issue with moving the hosting is that I need to get the database off of my server, and I can't do that until it's paid for.
I'm definitely open to help with hosting it but main thing is we need to get the database otherwise all the links are gone. If people want to pitch in for the bill that would be incredibly helpful.

![Screenshot_20200317_064348](https://user-images.githubusercontent.com/9222609/76794521-4ccb0280-681b-11ea-8552-788bbfe095f4.jpg)

I have a PayPal https://www.paypal.me/willb321

And a patreon https://www.patreon.com/coriolis_elite

I'd recommend the PayPal since I don't think patreon pays out till the 1st.

**Comment by rosscarlson** [comment]
So let's be blunt - are we at a place where if the community doesn't come up with $126.22 then we're going to lose every one of the existing links? I can't imagine how the hell it's that expensive (I mean I see it but WOW) as I pay $40/month for a fully dedicated VM at AWS where it could be hosted long term.

I'm willing to consider that in terms of covering that cost, at least in the short term until your Patreon pays out with you paying me back some percentage, if the plan was to move this permanently, along with Coriolis.io to our AWS hosting at EDT so that I/we can ensure something like this doesn't happen again. I'm flexible on how this would happen with you remaining in control of the AWS server dedicated to you. I do use the tool very heavily and my users benefit from it greatly and bluntly it would likely take me so much time to recreate and change every single link on the 200+ videos I have that my time is more valuable than this. 

Here's what I'd like to do - can you ping me via Discord so we can discuss how we can move this forward? Can you ping me via the Level 11 Discord (https://discord.gg/ScxyTS8) so we can discuss? I just want to ensure that something like this doesn't happen again and as the entire goal behind EDTutorials.com is to bring the community together into one place I would very much be interested in making Coriolis part of what we're doing.

Hope to hear from you soon.  ~Exigeous

**Comment by AlexandrosG** [comment]
Just to note that it's Australian dollars which comes up to like 77 US dollars, so not that expensive.

I hope you guys can figure it out and get this thing online cause it's a pain to have like 90% of the links posted on reddit, ED forums etc down for a week now. Although I don't agree much with having a tool like this rely so heavily on a content creator who's here and now and gone the next day. Maybe down the line you hold his DB hostage again and we're stuck in the same situation.

Anyway, hope you can find a solution and in the meanwhile, please let us know how much more you need to pay off the bill...

**Comment by rosscarlson** [comment]
Actually another question/issue - if we're just going to move the site do we even need to worry about that bill? If we move hosting over to our AWS instances at EDTutorials.com then we can just update DNS to point there. We'd just need to get the code setup (which I can't imagine is that complicated) and bingo, we're done. No need to pay hosting fees, etc.

And good to know that it's in Aussie dollars, still pretty damn expensive given I get a full virtual server that hosts all the traffic we get to EDTutorials.com - and while we're not nearly as popular it's also a much larger site so I'd expect hosting to be more demanding.

Regardless hoping to hear from you very very soon @willyb321

**Comment by AlexandrosG** [comment]
I'll assume that he doesn't have a backup of the database that saves the shotcodes that refer to the builds on coriolis.io and the old hosting company won't allow him to get the database.

Without the database, all the shortlinks won't work. Even if you switch the DNS to your server, the shortener is useless without the DB that matches shortner URL with coriolis.io URL

**Comment by damianb** [comment]
@AlexandrosG assuming that one were to implement the backups as a cross-account solution in AWS, there can actually be a guarantee that there isn't a database being held hostage (assuming that willy would be willing to pay for just the S3 storage costs of the database backups, which when you add in object retention policies, would make it a fairly trivial cost in comparison to the cost of a full database).  You can fairly easily do a PutObject into another account, assuming correct IAM configuration.  It does cost a little more but it's fractional costs, and even for a daily backup it wouldn't cost much at all.  As long as there's no DeleteObject IAM permission, that's your guard against such a possibility.

Now's probably the time to consider a patreon or somesuch for coriolis though, if it's worth trying to have the community chip in a few bucks to pay for the hosting.  I'd recommend that over advertising, considering how much of the internet-savvy population blocks ads, and how many advertisers (i.e. google) do everything they can to actually avoid paying out.

**Comment by damianb** [comment]
@willyb321 you probably need to make the patreon a little more easy to find via coriolis or github.

**Comment by rosscarlson** [comment]
@willyb321 Pinged you in Discord as I need to make some kind of decision in the next day as to what I'm going to do, either move to something else and go through the pain of recreating and updating every single link on 200+ videos or work with you to get the server back and migrate it to an AWS instance with EDTutorials.

Looking forward to getting this resolved.

**Comment by danbt79** [comment]
Good job @rosscarlson.

If @willyb321 isn't capable of resolving the current issues without requiring finances from the community - or simply doesn't have the time available - and is unwilling to take you up on an offer of more cost-effective hosting, and the time to help - then I say do it anyway.

Fork and host on a new domain. Update your links. Explain on YouTube. The rest will follow. o7

**Comment by willyb321** [comment]
FYI the servers are back up at the moment and I will be negotiating alternative hosting in the near future. (I've had a few different offers for hosting help.)

Will keep this open for the moment.

**Comment by Jibsman** [comment]
With the donations to date, how much more do you need? US Dollars please.
I came here to complain about being unable to go to the updated site and the shortner being broken, but if you are having problems due to a funding shortage I recommend some sort of "GoFundMe" and advertise it on Reddit, etc.  I can provide a few US $$ but not the whole thing.

**Comment by danbt79** [comment]
That’s great news @willyb321 - thank you. Do ask for help if you need it! That can be skills, not just money, if your time is limited. 👍🏼

**Comment by Sortam** [comment]
It seems that both services are down again - Error 522 for three days as for now.

**Comment by vanderaj** [comment]
@willyb321 If you need help paying for hosting, please do make a public fund raiser in r/EliteDangerous. I'm sure there are many of us who would gladly pay a small amount each month for such an essential service. If there's anything I can do to help with hosting, please let me know. I have a spare box at Linode that you could use, but I think it would be just as easy for you to fire up a node there - they're about $25 per month for a half decent configuration, more if you need a beefier server. My forum handles about 100,000 hits per day, and it never breaks a sweat.

**Comment by DoomHamster** [comment]
I'm actually kinda concerned for @willyb321 's welfare at this point.  Are you OK, mate?  If it's funding you need, I and probably a good portion of the community are willing to contribute!  If it's technical expertise, a lot of us can help there too!

**Comment by willyb321** [comment]
at the moment I'm working on getting this sorted with someone who will be providing hosting its just taking longer than anticipated.

**Comment by willyb321** [comment]
Also, I always forget to reply on GitHub to be sure to check out the discord https://discord.gg/zQjjutY

**Comment by GitHub0Abby** [comment]
Coriolis still down, was up a few days ago.
ERR_CONNECTION_TIMED_OUT
any news? nothing in discord either ...

**Comment by GitHub0Abby** [comment]
Coriolis still down, was up a few days ago.
ERR_CONNECTION_TIMED_OUT
any news? nothing in discord either ...

**Comment by Sortam** [comment]
> Coriolis still down, was up a few days ago.
> ERR_CONNECTION_TIMED_OUT
> any news? nothing in discord either ...

Works very well and fast for me @GitHub0Abby . It seems that you have some Internet issues, even your comment was posted 4 times.

**Comment by GitHub0Abby** [comment]
thx for reply, but it seems that it's just me that cannot get easy use of github ...
and for coriolis i can access to site now (couldn't when i posted and used 3 proxys to check and same there) but still cannot use links with "?code=" values ... any info on that by any chance?
Thx

**Comment by felixlinker** [comment]
@willyb321 This issue is resolved, right?
