### ISSUE TITLE
Wrong Stats for Long Range Interdictor

### ISSUE THREAD

**Issue by srguglielmo** [EDCD/coriolis#612]
Hello,

When engineering a grade 1 long-range FSD interdictor, the in-game stats are:

- Mass +10%
- Power Draw +10%
- Facing Limit -10%
- Range +20%

However, coriolis.io claims Facing Limit is -1%. Seems like it's off by a factor of 10.

I quickly looked through the code, but couldn't find where it is defined. I'm happy to submit a PR if you point me to the right file?

Thanks!

**Comment by felixlinker** [comment]
Thanks for your report and the willingness to step in! Long-range interdictor is defined here: https://github.com/EDCD/coriolis-data/blob/master/modifications/blueprints.json#L2331

If you create a PR, please fork and target dev branch. It would be great, though, if you could look at all the grades then. Otherwise, we might get issues from non-monotonicity.

**Comment by spacek531** [comment]
since this issue is still open, I'll add that G5 blueprints exist for interdictors, available at Mel Brandon
![EliteDangerous64_2021-01-13_16-23-17](https://user-images.githubusercontent.com/3454156/104528411-06ba0900-55bc-11eb-8a14-1a208d13c1b9.png)
![EliteDangerous64_2021-01-13_16-23-23](https://user-images.githubusercontent.com/3454156/104528418-0de11700-55bc-11eb-93ca-8e62b685029f.png)
