### ISSUE TITLE
ENG pips do not influence all turn axes

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#634]

**Comment by neilser** [comment]
The pips are definitely influencing the numbers for all three axes in the "profiles" display for me when I use Coriolis. Not certain this is also true in the game but I always believed that was the case.
The title of this issue is ambiguous - does it mean that the ENG pips don't influence all turn axes in game, unlike in Coriolis, and thus Coriolis shouldn't show the pips as influencing them?

**Comment by felixlinker** [comment]
The issue is about how the game works. Thanks for pointing this out.

**Comment by neilser** [comment]
OK yeah I just did some tests in a Sidewinder, which is meant to be hugely sensitive to the engine pips (with a pipSpeed of ~0.136).
Results: roll and yaw didn't respond at all to the engine pips. Gosh... Not what I was expecting but I guess that's why this issue exists :)

Also, the influence on pitch rate was MUCH smaller than Coriolis calculates - I measured 42 deg/s at 4 pips (Coriolis indicates 43 for my ship, so basically perfect) but 34 deg/s at 0 pips (Coriolis calculates 20!).

I estimate the true pipSpeed for my ship to be around 0.045 - have FD changed ship behaviours?

**Comment by felixlinker** [comment]
Thanks for running the extra tests! This is interesting data. Did you turn while being in the blue zone?

**Comment by neilser** [comment]
Yup, tried it in blue zone and stopped. Lemme try to attach my test results - I just did the T9 as well.
[pips_testing.txt](https://github.com/EDCD/coriolis/files/6030437/pips_testing.txt)

**Comment by felixlinker** [comment]
Had a user run tests who reported that 0 pips *increased* yaw rate.

**Comment by alex-williams** [comment]
Closing this issue, as there are various issues with the way pips work in Coriolis and it all needs to be re-done. Wep time to drain is wrong, affect on thrust is wrong, etc. The separate issue isn't needed.
