### ISSUE TITLE
Diamondback Explorer Missing Slots

### ISSUE THREAD

**Issue by Dunkelmann** [EDCD/coriolis#693]
Coriolis: Classes 4, 4, 3, 3, 2, 2, 1, 1 Optional Internal Slots
Elite Dangerous: Classes 4, 4, 3, 3, 2, SRV Bay, 2, 1, 1, 1 Optional Internal Slots

Missing:
a) SRV Bay 
b) Class 1 slot

**Comment by ehlrh** [comment]
The SRV Bay slot is actually part of your SRV Bay outfit. If you remove it the slot goes away with it, it's not a part of the ship. The bottom class 1 slot isn't an actual optional outfitting slot but rather a dedicated slot for the PAS, all ships have this and it's not reflected for any of them because it's not changeable.

**Comment by Thedoczek** [comment]
Case should be closed since it's fixed by now
