### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier 'many'

### ISSUE THREAD

**Issue by C12ASHD** [EDCD/coriolis#743]
Have been receiving this error alot lately while trying to import my ship from EDDI to Coriolis. the following is the details requested for the error.
 Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Path: /
Error: Unknown
Details:
scriptUrl: https://coriolis.io/
line: 1
col: 14
error: {}

**Comment by alex-williams** [comment]
Closing this as being fixed by the fix for #754 . Although there is no error detail here to be certain that this issue is related, the vast majority of import issues in Coriolis have been related to missing modules, which is now resolved (at least in beta) by the addition of both improved importing and by adding the majority of the modules that were missing up to this point.
