### ISSUE TITLE
Power distributor bug

### ISSUE THREAD

**Issue by aaaaettvgrr** [EDCD/coriolis#764]
There appears to be a new power disrubuiter, but it seems to not exist, and has a class of OZ, 
![IMG_3174](https://github.com/EDCD/coriolis/assets/168147005/384f113f-c4fb-4aac-a52b-02e1febb2498)

I don’t know what that is there for,

**Comment by alex-williams** [comment]
This bug exists due to #754 I did originally prevent this from happening (or thought I did) and only seems to happen on certain modules, specifically:

Distro
FSD
Power Plant

It only occurs on https://beta.coriolis.io as the changes have not yet been migrated to live.

The 'Missing Module' Category, also shows up when selecting internal modules and it should not.

**Comment by alex-williams** [comment]
Fix deployed to Live Site after a period on beta.coriolis.io.
