### ISSUE TITLE
Validate user input

### ISSUE THREAD

**Issue by z0rc** [EDCD/coriolis#78]
With a bit of tinkering it's possible to build something like this https://coriolis.edcd.io/outfit/orca?code=A4putuFplsdusif8Ap0x0x0x0x0x0xmn2d2dp72b29m3m3.Iw18SQ%3D%3D.CwBj4ypI.H4sIAAAAAAAAA3WSPU4DMRCFJz8bNnGyjjebEEBIkCwU0NAiIXECJCQoKDkNp6DILbhGCgoKDkCFoENCePCbxXa0WlK8jDPfm3mRhmxKRD%2BJE3P9zVyuNFH%2B%2BcI8Wj20SK3fmbllLz2UrreI9NkX82yc%2FZHctjPf1wcdomJomae3imiO5%2FLCz%2BSO3Q0k1hVYMkdrgqqCutVXYs89e4TmMWQBOQyuAao%2BREd%2Fam%2B8MRHy%2FoNZWoRnF9LDcxvVDmSJ5ymqfQj37Z0fIcYkeAQXIw%2BaoNgXnFWE4hAddka8yj6MuEbs6MlD4nkwyggebXhek809%2F3uymqf2Lxs94xK1gchxZHIhMbuxJ36mtMyTK0uICp6KzO2VJ9vP7lZ6b%2B5MFHIYyBTk3qMDy5BNLoUncYX8WkukQiwuamFiBBNyiNtdRcPnF49BYtoYAwAA&bn=Taco%27s%20Joybus%20v2

Please ensure that data created/modified by user is actually valid in given ship limitations.

**Comment by cmdrmcdonald** [comment]
There is no information available on engineering secondaries, so there is no way to place definite limits on the values that engineered modifications can go to.  The only limits in place are -99.999% and +1000%, for internal purposes.

**Comment by z0rc** [comment]
Engineering aside, what about fitting 8 sized powerplant in 5 sized slot and similar?

**Comment by z0rc** [comment]
Or fitting weapons into utility mounts?

**Comment by Athanasius** [comment]
If you intentionally break it that badly you get to keep all the pieces.

**Comment by z0rc** [comment]
This is intentionally created to show the issue.

I've had a case when someone boasted with his slightly unrealistic build created by the same approach that left a lot of others puzzled how did he archived this in game. Proper size/mount type validation would save a lot of trouble here.

**Comment by cmdrmcdonald** [comment]
Manually altering the URL can give you these things, and they have been used in the past for 'what if' modelling (e.g. what happens if the Corvette is given a larger FSD, what if the FdL obtained a larger power plant, what if the type-7 had larger internals?) that have been very useful when discussing potential changes to models.

I'm not planning on adding any URL validation for this reason, so as long as they can't be created during normal use of Coriolis I'm not considering it a bug.
