### ISSUE TITLE
Minor rounding errors in power plant

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#8]
After entering all engineer modifications for my 8A power plant, the game reports it now provides 39.75MW of power while coriolis reports 39.74MW. Same with retracted and deployed. The game reports 28.27MW retracted while coriolis reports 28.26MW and the game says 37.09MW deployed while coriolis reports 37.08MW.

**Comment by cmdrmcdonald** [comment]
Please could you provide your beta.coriolis.edcd.io URL that shows this configuration, along with a screenshot of your powerplant modifications, so that we can hunt this issue down?  Thank you.

**Comment by nemesyssoft** [comment]
Here:
http://beta.coriolis.edcd.io/outfit/imperial_cutter/2putxFplxdusCf60x7l7l1c1c0t0t020g060404040404070705p1f6045i322f.Iw18ZZA=.IzAM-MOnJV4iA===.,integrity:-530;eff:750;pGen:1040,integrity:-230;power:140;optmass:-120;optmul:1420;thermload:3300,mass:1670;integrity:-2230;power:2350;thermload:-70;optmass:4670,,power:-630;wepcap:1930;weprate:910;engrate:-430;syscap:-441;sysrate:-200,,,,,,,,,,,,,explres:420;integrity:940;kinres:420;mass:440;power:190;shieldmul:2000;thermres:420,explres:466;kinres:466;thermres:466;integrity:-150;power:520,,,,,,,mass:-230;optmass:919;brokenregen:-2020;kinres:149;thermres:298?bn=Kantos%20Kan%20Cutter

Here is a link to a screenshot from the outfitting screen showing the PP mods:
[http://i.imgur.com/ebTXDSX.jpg](url)

**Comment by cmdrmcdonald** [comment]
These rounding errors are due to FD only showing one decimal place on their modifications UI.  For example, if you set your power plant generation modifier to 10.41% then the value shown in coriolis is now accurate.

I'm in the process of writing documentation that explains how third-party tool developers can take modification information from the companion API and turn it in to a coriolis URL, which would provide the required level of accuracy for all values.
