### ISSUE TITLE
Can we make the presets less bad?

### ISSUE THREAD

**Issue by Taverius** [EDCD/coriolis#81]
The shielded trader can be renamed 'suicide trader'
The miner is shieldless with an undersized distributor, when you basically guaranteed to be interdicted with a hold full of stuff

What do you need to improve them? Are they set programmatically or does someone have to give you build for each ship/preset combination?

**Comment by cmdrmcdonald** [comment]
The idea of the shielded variants of the trader and miner is to provide a shield that survives bumps and scrapes rather than combat, and as such puts in the smallest variant possible for each ship.

There is no way that a single preset can cater to every crowd, so it's designed to give you the maximum miner/trader/whatever with minimal shield.  Users can, of course, upgrade as they see fit.
